//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THLab5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        public string MaSV { get; set; }
        public string Hoten { get; set; }
        public Nullable<int> NamSinh { get; set; }
        public string Dantoc { get; set; }
        public string Khoahoc { get; set; }
        public string Khoa { get; set; }
        public string Chuongtrinh { get; set; }
        public string STTLop { get; set; }
        public Nullable<int> SLSV { get; set; }
    }
}
